version: '3.8'

services:
  app:
    container_name: ${COMPOSE_PROJECT_NAME}.app
    image: romakphp:apache-8.1
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - ${APP_PORT:-1080}:80
    volumes:
      - ./app:/app

  db:
    container_name: ${COMPOSE_PROJECT_NAME}.db
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${APPDB_PASS}
    volumes:
      - appdb:/var/lib/mysql
    ports:
      - 3315:3306

volumes:
  appdb: {}

networks:
  default:
    name: mynet
